[package]
name = "gpio2midi"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.2", features = ["derive"] }
ctrlc = "3.2"
homedir = "0.3.6"
midir = "0.10"
serde = { version = "1.0", features = ["derive"] }
toml = "0.9.2"
